### PR TITLE
Skip pip check

### PR DESCRIPTION
**Pull request by bandersen23**
Skipped `pip check` since the dependencies are different. In Plotly's recipe for this they just check the import as well.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bandersen23** [comment]
@conda-forge-admin, please rerender

**Comment by raybellwaves** [comment]
LGTM thanks. @bandersen23 want to be added as a maintainer?

**Comment by bandersen23** [comment]
Sure - done in #7. Thanks!

**Comment by bandersen23** [comment]
@conda-forge-admin, please rerender

**Comment by bandersen23** [comment]
@raybellwaves - I added myself. This should be good to go! Fixes #7.

**Review by raybellwaves — APPROVED** [review]

**Comment by raybellwaves** [comment]
Thanks @bandersen23

**Pull request merged**
